### ISSUE TITLE
Install and configure Jenkins

### ISSUE THREAD

**Issue by israelboudoux** [maticnetwork/nightfall-sdk#10]
Install and configure Jenkins on AWS and create a job for the current Nightfall repositories.
Installation/configuration steps:
- Install the app;
- Install/configure plugins;
- Enable Jenkins data backup;
- Create admin credentials;
- Add system admin e-mail (iboudoux@polygon.technology);
- Configure a proper domain for access Jenkins (e.g. jenkins.nightfall.com) only via VPN (Internal);
- Install/Configure github Jenkins credentials;
- Configure HTTPS:
	- Create selfsigned certificate;
	- Disable HTTP.
- Create team credentials via Github webhook (for the moment only @druiz0992 and I have full access);
- Configure job for nightfall3 repository.

**Comment by israelboudoux** [comment]
I decided instead of just writing a document with the comparison among the tools, to give a try for each of them by installing and configuring some jobs/tasks that we are going to use/need so that the team can test them as well and give their impressions about them.

**Comment by israelboudoux** [comment]
When trying to make Jenkins to accept connections via HTTPS I was faced with the following issue:

`java.lang.SecurityException: class "Log4jHotPatch"'s signer information does not match signer information of other classes in the same package
	at java.base/java.lang.ClassLoader.checkCerts(ClassLoader.java:1151)
	at java.base/java.lang.ClassLoader.preDefineClass(ClassLoader.java:906)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1015)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:431)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallAgentmain(InstrumentationImpl.java:535)
`


It is related to an [issue](https://github.com/corretto/hotpatch-for-apache-log4j2/issues/53) that is still Open. I'll move forward and try to come back later to the HTTPS thing. Since Jenkins can only be accessed via VPN, we are safe for now.

**Comment by israelboudoux** [comment]
The S3 Bucket is now created for accommodate the Jenkins data backup: nightfall-cicd-backup
The Jenkins plugin `Periodic Backup` will manage the backup. Following the current configuration for the periodic backup, only the last 7 days will be kept on the bucket and the backup will happen everyday about 00:00. 

![Screenshot from 2022-06-07 15-14-03.png](https://images.zenhubusercontent.com/628cfcd267c6f7c6859003d2/b4dcabbe-d88d-4e06-ab2d-d47279b47cc8)

The backup was tested successfully!
![Screenshot from 2022-06-07 15-07-41.png](https://images.zenhubusercontent.com/628cfcd267c6f7c6859003d2/e1e94075-9bf9-49dc-8c26-187d71f62aa3)

**Comment by israelboudoux** [comment]
Jenkins is now accessible via the following URL:
http://jenkins.polygon-nightfall.technology:8080

I still need to manage to do it accessible only via HTTPS.

**Comment by israelboudoux** [comment]
Jenkins is now accessible via HTTPS
https://jenkins.polygon-nightfall.technology:8443/

**Comment by israelboudoux** [comment]
Jenkins is now available to the team members and the authentication is being done via Github.

**Comment by israelboudoux** [comment]
Jenkins is now configured with a job for Nightfall3, but it is still unable to build it, since it needs a Jenkinsfile properly configured with the current Nightfall actions that are done on Github Actions.
