### ISSUE TITLE
fix: EVM reverts approval transaction

### ISSUE THREAD

**Issue by imagobea** [maticnetwork/nightfall-sdk#67]
### Context

When performing a deposit, the value must be smaller than the allowance set for the spender (in the token contract). This bug has come to light when running the SDK against ganache since every time you `./start-nigtfall -g`, you run a fresh instance of the ganache blockchain. Which means allowance is always 0, therefore you need to go through the approval step.

### Error logs

```bash
[2022-07-28 20:35:26] DEBUG (libs/tokens/token.ts): ERC allowance vs tx value
    allowanceBN: "0"
    valueBN: "186a0"
[2022-07-28 20:35:26] INFO (libs/transactions/approval.ts): Approval tx, unsigned
    unsignedTx: "0x095ea7b3000000000000000000000000864d794ab771516adbd058366e72ba697273eb53ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"
[2022-07-28 20:35:26] DEBUG (libs/transactions/helpers/submit.ts): submitTransaction
    logInput: {
      "from": "0x9C8B2276D490141Ae1440Da660E470E7C0349C63",
      "to": "0x4f3c4F8D4575Cf73c2FAf9F36cc505e19E65B9C0",
      "unsignedTx": "0x095ea7b3000000000000000000000000864d794ab771516adbd058366e72ba697273eb53ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
      "fee": "21000000000"
    }
[2022-07-28 20:35:26] DEBUG (libs/transactions/helpers/submit.ts): Transaction gasPrice was set at 20 GWei, gas limit was set at 8000000
null
Nightfall tx hashes :: []
{ balance: {} }
Bye bye
[2022-07-28 20:35:26] ERROR (libs/transactions/approval.ts): Transaction has been reverted by the EVM:
{
  "transactionHash": "0xe91aa9d14c966042415a6ff301ba70871a1c3c929627afac605c4f4b28337398",
  "transactionIndex": 0,
  "blockHash": "0xdbd19cdb3611f78a46c97492ab700058a10b7e05f912fc7256bfdc776c0dc420",
  "blockNumber": 896,
  "from": "0x9c8b2276d490141ae1440da660e470e7c0349c63",
  "to": "0x4f3c4f8d4575cf73c2faf9f36cc505e19e65b9c0",
  "gasUsed": 21989,
  "cumulativeGasUsed": 21989,
  "contractAddress": null,
  "logs": [],
  "status": false,
  "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
}
    unsignedTx: "0x095ea7b3000000000000000000000000864d794ab771516adbd058366e72ba697273eb53ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"
    err: {
      "type": "Error",
      "message": "Transaction has been reverted by the EVM:\n{\n  \"transactionHash\": \"0xe91aa9d14c966042415a6ff301ba70871a1c3c929627afac605c4f4b28337398\",\n  \"transactionIndex\": 0,\n  \"blockHash\": \"0xdbd19cdb3611f78a46c97492ab700058a10b7e05f912fc7256bfdc776c0dc420\",\n  \"blockNumber\": 896,\n  \"from\": \"0x9c8b2276d490141ae1440da660e470e7c0349c63\",\n  \"to\": \"0x4f3c4f8d4575cf73c2faf9f36cc505e19e65b9c0\",\n  \"gasUsed\": 21989,\n  \"cumulativeGasUsed\": 21989,\n  \"contractAddress\": null,\n  \"logs\": [],\n  \"status\": false,\n  \"logsBloom\": \"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000\"\n}",
      "stack":
          Error: Transaction has been reverted by the EVM:
          {
            "transactionHash": "0xe91aa9d14c966042415a6ff301ba70871a1c3c929627afac605c4f4b28337398",
            "transactionIndex": 0,
            "blockHash": "0xdbd19cdb3611f78a46c97492ab700058a10b7e05f912fc7256bfdc776c0dc420",
            "blockNumber": 896,
            "from": "0x9c8b2276d490141ae1440da660e470e7c0349c63",
            "to": "0x4f3c4f8d4575cf73c2faf9f36cc505e19e65b9c0",
            "gasUsed": 21989,
            "cumulativeGasUsed": 21989,
            "contractAddress": null,
            "logs": [],
            "status": false,
            "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
          }
              at Object.TransactionError (/home/bea/Dev/Polygon/nightfall-sdk/node_modules/web3-core-helpers/lib/errors.js:87:21)
              at Object.TransactionRevertedWithoutReasonError (/home/bea/Dev/Polygon/nightfall-sdk/node_modules/web3-core-helpers/lib/errors.js:98:21)
              at /home/bea/Dev/Polygon/nightfall-sdk/node_modules/web3-core-method/lib/index.js:396:57
              at processTicksAndRejections (internal/process/task_queues.js:93:5)
      "receipt": {
        "transactionHash": "0xe91aa9d14c966042415a6ff301ba70871a1c3c929627afac605c4f4b28337398",
        "transactionIndex": 0,
        "blockHash": "0xdbd19cdb3611f78a46c97492ab700058a10b7e05f912fc7256bfdc776c0dc420",
        "blockNumber": 896,
        "from": "0x9c8b2276d490141ae1440da660e470e7c0349c63",
        "to": "0x4f3c4f8d4575cf73c2faf9f36cc505e19e65b9c0",
        "gasUsed": 21989,
        "cumulativeGasUsed": 21989,
        "contractAddress": null,
        "logs": [],
        "status": false,
        "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
      }
    }
```

### Solution

TBC

**Comment by luizoamorim** [comment]
@imagobea I was doing some tests. If remove the gasPrice and fee of the TX created the error doesn't happens.
After that I added the gasPrice and fee again and the deposit is working normally.
Let's try together tomorrow.

**Comment by imagobea** [comment]
Well spotted @luizoamorim I think you are right and the issue is around the tx submission (after creating the "approval - unsigned tx"). So it makes sense that the error is about gas estimation. Looking fw to our chat!!
